userstorycreator_task:
  description: >
    Review Business Rules: Understand the below business rules and create Jira User stories.
            Business Rules: {topic}
        User Story Formatting: For each business rule, create a Jira User Story in the format:
            Title: A concise summary (e.g., "As a [role], I want to [action], so that [benefit].")
            Acceptance Criteria: List the conditions required for the User Story to be considered complete.
            Dependencies: Document any dependencies or related systems (e.g., mainframe-specific details).
            Technical Notes: Include any technical constraints, limitations, or integration notes for mainframe systems to help developers understand the context.
        Additional Details:
            Ensure clarity in language for both technical and non-technical stakeholders.
            Prioritize stories based on dependency mapping or business importance if known
  expected_output: >
    A collection of Jira User Stories with corresponding Acceptance Criteria, Technical Notes, and Dependencies.
  agent: userstorycreator


# User story reviewer task
userstoryreviewer_task:
  description: >
    Review Jira User Stories: Review the Jira User Stories created by agent userstorycreator and ensure they meet the business requirements.
    Ensure the stories are clear, concise, and aligned with the business rules.
    Check for any missing or incorrect information.
    If any issues are found, provide suggestions for improvement.
  expected_output: >
    The output will contain a JSON file with a collection of Jira User Stories with corresponding Name, Title, Acceptance Criteria, Technical Notes, Dependencies, Additional Criteria if applicable and nothing additional.
  agent: userstoryreviewer


